### ISSUE TITLE
Update deploy.sh to validate if kruize is running, if not exit with failures status

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#28]
icp_deploy method should validate if kruize is running and if not exit with failed status.

kruize-57d465b544-c576b                                        0/1     InvalidImageName             0          2s

**Comment by dinogun** [comment]
This should be fixed now, please check.

**Comment by dinogun** [comment]
@chandrams Can you please validate to see if this fixed

**Comment by chandrams** [comment]
This is fixed now.

**Comment by chandrams** [comment]
This still fails - http://9.199.149.41:8080/job/kruize_test_pipeline/195/console

Shouldn't we exit with failure code in check_running() instead of break? Also  when the pod state is in "ContainerCreating"|"Terminating"|"Pending" -  shouldn't we break from the inifinite while after some retries if pod state doesn't change?
